language: cpp

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq libstdc++-4.8-dev; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - mkdir /tmp/lld
  - mv * /tmp/lld
  - git clone --depth=1 https://github.com/avr-llvm/llvm llvm
  - mv /tmp/lld llvm/tools/
  - cd llvm/

script:
  - ./configure --enable-targets=avr
  - make -j 1
